---
abstract: 'Analyze OTRS add-ons (.opm files)'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OTRS-OPM-Analyzer
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  HTML::Lint: 0
  LWP::Simple: 0
  MIME::Base64: 0
  Module::CoreList: 0
  Module::OTRS::CoreList: 0
  Moose: 0
  Moose::Role: 0
  PPI: 0
  Path::Class: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Software::License: 0
  Software::LicenseUtils: 0
  Test::Exception: 0
  Test::More: 0
  Text::Diff: 0
  Try::Tiny: 0
  XML::LibXML: 0
  YAML::Tiny: 0
resources:
  bugtracker: http://github.com/reneeb/OTRS-OPM-Analyzer/issues
  homepage: http://github.com/reneeb/OTRS-OPM-Analyzer
  repository: http://github.com/reneeb/OTRS-OPM-Analyzer.git
version: 0.03
